micronaut:
  application:
    name: devchallenges
  server:
    max-request-size: '100MB'
    multipart:
      max-file-size: '100MB'
    port: 5000
    cors:
      enabled: true
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      documentation:
        paths: classpath:META-INF/swagger/views/rapidoc
        mapping: /docs/**
      files:
        paths: file:${DEV_CHALLENGE:`D:/Dev/files`}
        mapping: /files/**

files: 
  path: ${DEV_CHALLENGE:`D:/Dev/files`}
  allowed-extensions:
    - jpg
    - png 
    - gif
    - jpeg
    - svg